### ISSUE TITLE
Tag A for Link

### ISSUE THREAD

**Issue by gfazioli** [joelambert/Flux-Slider#10]
Hi,
I have some problem to catch link in:

Example:
```<div id="slider">
  <a href="#link1"><img src="a.png" /></a>
  <a href="#link2"><img src="a.png" /></a>
  <a href="#link3"><img src="a.png" /></a>
</div>

```

Is link unsupported? Or I wrong something in CSS?

regards
GF
```

**Comment by joelambert** [comment]
Hi, 

This is not currently supported - will try and add this for the next release

Joe

**Comment by gfazioli** [comment]
Thanks

**Comment by joelambert** [comment]
This should now work in the pre-release version available in the GitHub repo, let me know if you have any problems.

**Comment by gfazioli** [comment]
Amazing! ;)
