### ISSUE TITLE
jQuery noConflict

### ISSUE THREAD

**Issue by basti1253** [joelambert/Flux-Slider#14]
Hi,

please wrap your code inside a closure so jQuery.noConflict works as expected.

This worked for me:

(function ($) {
  //..
  window.flux = flux;
} )( jQuery );

Can't open a pull request from here as I am in customers buro atm. If you want me to fork and pull that let me know.

best regards and nice work

Sebastian

**Comment by joelambert** [comment]
Hi Sebastian,

Have you tried the most recent (unreleased) code in the Github master? It should work when jQuery is in compatibility mode

Thanks

Joe

**Comment by basti1253** [comment]
No I didn't ;) _closes "issue"_

**Comment by joelambert** [comment]
Cool, glad its working for you :)
