### ISSUE TITLE
Move the CSS styles out of JS

### ISSUE THREAD

**Issue by avaly** [joelambert/Flux-Slider#15]
The CSS styles for the helper elements (pagination, caption, next/previous links) should be moved to an external CSS file, to allow easy overriding and customization. Otherwise, we have to use the !important flag to override the inline styles set by the JS code.

The next/previous buttons don't even have a class name set, so customizing them without CSS3 selectors is very difficult.

**Comment by joelambert** [comment]
Hi,

Yeah this is on the roadmap & I agree that its important so that custom styling can be applied without the dreaded `!important`.

I'll close this ticket when its done, thanks again for the feedback
