### ISSUE TITLE
Prevent running on FF<4

### ISSUE THREAD

**Issue by joelambert** [joelambert/Flux-Slider#16]
> Is there any way not to display it on any versions of FF < 4?

What is your usecase for this? Is is that you don't want it to run in FF<4 because it doesn't support transitions? If so then a better solution is to only show Flux when CSS transitions are supported by the browser.

To do this you can do something like

```
if(flux.browser.supportsTransitions) {
    window.f = new flux.slider('#slider');
}
else {
    // Do something else
}
```

If instead you have some genuine need to do browser sniffing then I suggest you search for regex expressions for filtering FF<4

Hope that helps?

**Comment by ghost** [comment]
OK thanks, that's basically what I was trying to achieve. When I tested it in Firefox 3.6 or something it broke and only displayed the images under each other.

Thanks again. 

Also, I was wondering if you could please finish that little bit of code off by making it not show if CSS transitions are not supported...?

**Comment by joelambert** [comment]
Have you tried downloading the [pre-release code for v1.4](https://github.com/joelambert/Flux-Slider/blob/master/js/flux.js) in the GitHub repo?

It should fix the behaviour your describing and degrades better in un-supported browsers. In browsers that don't support transitions the slider will now still show and just switches between images

**Comment by ghost** [comment]
Oh that's great, thanks a bunch. :)
