### ISSUE TITLE
choose transitions

### ISSUE THREAD

**Issue by lucapost** [joelambert/Flux-Slider#19]
Can you post an example code for how to select transitions effect with array sintax?

**Comment by stivaugoin** [comment]
I want the same thing! I can't set just one transitions effect.

**Comment by joelambert** [comment]
Here's an example that uses just the `turn` and `bars3d` transitions:

```
window.myFlux = new flux.slider('#slider', { transitions: [ 'turn', 'bars3d' ] });
```

Hope that helps.

**Comment by chriswyn** [comment]
Thanks joelambert for the correct code for the transition array. perfect!

**Comment by thriveweb** [comment]
Hi. great script! Is it possible to assign a transition to a slide with Autoplay enabled?

**Comment by Dheerajmishra01** [comment]
How to make a slider image to full width
