### ISSUE TITLE
Website seems to be offline.

### ISSUE THREAD

**Issue by jayarjo** [joelambert/Flux-Slider#23]
If I go to: http://www.joelambert.co.uk/flux, I get ugly:

<blockquote><h1>Not Found</h1>

The requested URL /flux was not found on this server.
</blockquote>

**Comment by joelambert** [comment]
Thanks for reporting this, it appears that my host is temporarily down. I've reported the issue and will keep an eye on the site.

**Comment by joelambert** [comment]
Problem resolved
