### ISSUE TITLE
CSS 3D Transforms not detected on Firefox 10

### ISSUE THREAD

**Issue by gpetrov** [joelambert/Flux-Slider#26]
Now that Firefox 10 has CSS 3D transforms, the Flux Slider should use them but it still complains that the browser does not support 3D transforms.

Seems to me the detection code is wrong.

Hope you can fix it Joe!

Greetings,
   George Petrov

**Comment by joelambert** [comment]
Thanks for the report, I'll take a look into this and put up a patch. 

In the meantime if you use Flux in conjunction with Modernizr it should rectify the issue as it will use it's detect code instead.

**Comment by gpetrov** [comment]
Thanks Joe,

I don't use modernizr so will wait for your patch. 

It might be also good to check out the performance as it seems to me that the FF10 CSS 3D transforms aren't well optimized and possibly not hardware accelerated. Comparing with Chrome, the FF CSS 3D transforms are choppy and eat a lot of CPU.

So I hope you can make good use of them. If you find some interesting things - would love to see blog post about it :) I always enjoy those!

Here are some starting points from the mozilla:

http://romaxa.bolshe.net/css3d/poster/poster-circle.html
http://romaxa.bolshe.net/css3d/morphing/morphing-cubes.html

http://hacks.mozilla.org/2011/10/css-3d-transformations-in-firefox-nightly/

**Comment by nicmare** [comment]
yep. same problem here. i tried to dig into the flux code but cant find the related detection code :(

**Comment by joelambert** [comment]
I've managed to fix the detection code to work with Firefox10 but am having trouble with `-moz-perspective` on most of the 3D transitions.

Once I've managed to make them work I'll push an update up

**Comment by gpetrov** [comment]
You might also want get ready for IE10:
http://blogs.msdn.com/b/ie/archive/2012/02/02/css3-3d-transforms-in-ie10.aspx

Unfortunately to try IE10 now you need a Windows 8 installation :(

**Comment by joelambert** [comment]
This should now be fixed and available in the v1.4.3 tag.

Flux is now _mostly_ working with Firefox 10. The `blinds3d` effect is still a bit weird but I think this could be a bug in the Firefox implementation.

**Comment by nicmare** [comment]
thanks joe!
