### ISSUE TITLE
Fallback mode for older browsers?

### ISSUE THREAD

**Issue by jahvi** [joelambert/Flux-Slider#28]
Is there a plan to add some sort of graceful degradation for older browsers? As it is now it just stops working with an alert message, would be nice that it'd still work at least with a simple fade transition

**Comment by joelambert** [comment]
Flux does degrade to some degree already in that it just switches between the current and next image in unsupported browsers. The demo site throws an alert message instead but this wouldn't happen if you used it on your own site.

I've also written a simple fade fallback which I've included in the [WordPress Plugin](http://www.joelambert.co.uk/flux-wp) version of the code so it is possible to add your own custom fallback if needed.

**Comment by jahvi** [comment]
Great thanks for the response!
