### ISSUE TITLE
Blinds3D number of blinds?

### ISSUE THREAD

**Issue by threebean** [joelambert/Flux-Slider#29]
Hi,

Sorry if this is not the place to post such a question - can you specify the number of columns that make up the Blinds3D transition?

Thanks,
Steven

**Comment by joelambert** [comment]
Hi Steven,

This is a great place to ask, thanks for doing so!

Here's an example of how you can set the number of columns for a specific transition, in this case `blinds3d`:

http://jsfiddle.net/cT6MH/1/

Hope that helps, let me know

Thanks

**Comment by threebean** [comment]
Thank you - that's what i was looking for!

Thanks for putting this out there!
