### ISSUE TITLE
Specified Images size not taken into account. 

### ISSUE THREAD

**Issue by sledorze** [joelambert/Flux-Slider#3]
Unable to specify images size - requiered when they do not match.
Would be very usefull.

**Comment by joelambert** [comment]
This is on my list of things to do, its now a lot higher up the list - thanks for the feedback :)

I guess we've two options:
1. Make the slider the size of the smallest image it finds?
2. Allow a size to be specified in the options and assume the implementor doesn't give a size that is too large?

I think **2** is a nicer solution? 

I guess background scaling using `-webkit-background-size` could also be implemented for browsers that support it (WebKit & Opera only at the moment I think?) but thats a significantly more challenging exercise!

**Comment by sledorze** [comment]
2 is really the best I think :)

On Fri, Jun 10, 2011 at 4:25 PM, joelambert <
reply@reply.github.com>wrote:

> This is on my list of things to do, its now a lot higher up the list -
> thanks for the feedback :)
> 
> I guess we've two options:
> 1. Make the slider the size of the smallest image it finds?
> 2. Allow a size to be specified in the options and assume the implementor
>    doesn't give a size that is too large?
> 
> I think **2** is a nicer solution?
> 
> I guess background scaling using `-webkit-background-size` could also be
> implemented for browsers that support it (WebKit & Opera only at the moment
> I think?) but thats a significantly more challenging exercise!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/3#comment_1342647

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15
