### ISSUE TITLE
show numbers of current and total images

### ISSUE THREAD

**Issue by lucapost** [joelambert/Flux-Slider#33]
Similar of pagination, can you add output div to show current positions in images array like "[1-X]/X", where X is the numers of gallery images?

thanks,
LP

**Comment by joelambert** [comment]
Hi Luca,

This sort of output should be fairly simple to implement. Flux is open source so feel free to add the functionality yourself, if however you'd like to contract me to implement the feature send me a private message and we can work out an arrangement.

Thanks

Joe
