### ISSUE TITLE
How can we fit retina image within slider boundaries? 

### ISSUE THREAD

**Issue by Kloport** [joelambert/Flux-Slider#36]
Hi,
First off I wanted to thank you for this very fine piece of software.
Now my request: is there a way you can use images twice as big as the slider size without cropping them?
I tried to experiment a bit with jQuery but I couldn't come up with anything.
Do you have a clue?
Thank you very much and keep up the good work.
Yannick

**Comment by joelambert** [comment]
Not currently I'm afraid, the way the image is chopped up by the code assumes `1x` display.

As "retina" is becoming more prevalent across the web I may rewrite the way the cutting algorithm works, but I'm unlikely to have time to do this anytime soon I'm afraid :(

**Comment by Kloport** [comment]
Thank you for answering my request.
Keep up the good work, cheers.
