### ISSUE TITLE
IE 2D transitions Support 

### ISSUE THREAD

**Issue by gpetrov** [joelambert/Flux-Slider#37]
Hi Joe,

Yes I know this awesome slider is all about CSS 3D, but can you make it at least look good with 2D transitions in IE?

Nivo Slider has a pretty good old browser compatibility support... so it can still look pretty in IE.

At least use the 2D transforms from IE9 and do some basic transitions for older browsers.

That will be really cool and people can still see the slider even if they have an older browser.

Thanks your work is greatly appreciated!

-George

**Comment by joelambert** [comment]
Hi George,

Thanks for the complements. Unfortunately the issue isn't 3D vs 2D, its "old style javascript animations" vs "css transitions".

Flux uses CSS3 transitions exclusively for its 2D & 3D effects, unfortunately Microsoft didn't see fit to ship IE9 with CSS transition support. It should however be available in IE10 when its available.

Thanks

Joe
