### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by sledorze** [joelambert/Flux-Slider#4]
This one would be awesome..

**Comment by joelambert** [comment]
How do you mean? As in using Flux to transition from one video to another?

If so then unfortunately the technique used by Flux isn't transferable to videos.

**Comment by sledorze** [comment]
ah.. ok I though some video player (html 5 video tag) could work with it
(I've done some css3 transformation on one recently using chrome 12)..

On Fri, Jun 10, 2011 at 4:26 PM, joelambert <
reply@reply.github.com>wrote:

> How do you mean? As in using Flux to transition from one video to another?
> 
> If so then unfortunately the technique used by Flux isn't transferable to
> videos.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/4#comment_1342653

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15

**Comment by joelambert** [comment]
The only kinds of transitions that would work would be the ones like `cube` where the entire image/element is moved in one go.

For the other effects, I have to create multiple DOM elements for each 'slice/box' and put the image on the background, essentially cropping the image to that area of the screen.

Thats why its not possible to do these kinds of effects with Flux I'm afraid.

**Comment by sledorze** [comment]
ah.. ok make sense! :)
or switching to/from a video would then be done using a restricted set of
effects.......

On Fri, Jun 10, 2011 at 6:20 PM, joelambert <
reply@reply.github.com>wrote:

> The only kinds of transitions that would work would be the ones like `cube`
> where the entire image/element is moved in one go.
> 
> For the other effects, I have to create multiple DOM elements for each
> 'slice/box' and put the image on the background, essentially cropping the
> image to that area of the screen.
> 
> Thats why its not possible to do these kinds of effects with Flux I'm
> afraid.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/4#comment_1343396

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15

**Comment by altryne** [comment]
it IS possible :P
http://alexw.me/playground/canvas.html

**Comment by sledorze** [comment]
I see no css3 in there...

On Tue, Jun 14, 2011 at 4:37 PM, altryne <
reply@reply.github.com>wrote:

> it IS possible :P
> http://alexw.me/playground/canvas.html
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/4#issuecomment-1366348

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15

**Comment by altryne** [comment]
there's not any,
but I do the same exact thing we do in flux, with the images and background position

**Comment by sledorze** [comment]
ah ok :)
Would be AWESOME to be able to play videos.. (btw would need to be able to
wait for the end of the vid..)
Stephane

P.S.: have you seen the problem with the 3D bar effect in 1024x768?

On Tue, Jun 14, 2011 at 4:45 PM, altryne <
reply@reply.github.com>wrote:

> there's not any,
> but I do the same exact thing we do in flux, with the images and background
> position
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/4#issuecomment-1366408

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15

**Comment by altryne** [comment]
I personally don't think that videos will work with flux too much.
Flux is now targeted mostly to mobile, and to chrome/safari as they are the only ones who supports css3 3d.
Videos don't work too good on mobiles.
Leaving us with chrome/safari. Don't think it's much of a use case.

**Comment by sledorze** [comment]
my use case (for information) is digital signage, I generally use chrome and
build everything for it! ;)

On Tue, Jun 14, 2011 at 5:10 PM, altryne <
reply@reply.github.com>wrote:

> I personally don't think that videos will work with flux too much.
> Flux is now targeted mostly to mobile, and to chrome/safari as they are the
> only ones who supports css3 3d.
> Videos don't work too good on mobiles.
> Leaving us with chrome/safari. Don't think it's much of a use case.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelambert/Flux-Slider/issues/4#issuecomment-1366631

## 

Stphane Le Dorze

Tel: +33 (0) 6 08  76 70 15
