### ISSUE TITLE
Choose Only One Transition

### ISSUE THREAD

**Issue by qwert678** [joelambert/Flux-Slider#46]
How to Choose Only One Transition?
Thiw code does't work:
window.myFlux = new flux.slider('#slider', { transitions: [ 'turn', 'bars3d' ] });

**Comment by joelambert** [comment]
If you want to just use a single transition you should just list the name of the one you want to use:

```
window.myFlux = new flux.slider('#slider', { transitions: [ 'turn' ] });
```

Note, that if you're using IE10 there is currently a bug preventing 3D transitions working so the above will load all valid transitions instead.

**Comment by thriveweb** [comment]
Is it possible to assign a transition to a slide with Autoplay enabled?

Or can you have Autoplay without random transitions? 

Thanks!

**Comment by joelambert** [comment]
Not out of the box, you would need to disable auto play & write your own custom loop to handle getting the correct transition to use.
