### ISSUE TITLE
Possible memory leak on Safari

### ISSUE THREAD

**Issue by tuupola** [joelambert/Flux-Slider#50]
I am using Flux together with Zepto showing 1080p images on big television screen. Flux is used as kind of a screensaver.  There is also an information box over the image. This is just some HTML. Code is the following.

``` javascript
var screensaver = new flux.slider("#screensaver", {
    autoplay: true,
    delay: 12000,
    pagination: false,
    transitions: ["dissolve"],
    onTransitionEnd: function(data) {
        /* Show correct information box,*/
        var index = screensaver.currentImageIndex;
        $(".box").addClass("hidden");
        var box = "#box-" + index;
        $(box).removeClass("hidden");
    }
});
```

However I noticed that something leaks memory. When slideshow starts Safari Web Content uses 150MB memory.

![screenshot_353](https://f.cloud.github.com/assets/21913/1674487/1cc2ab0c-5cfa-11e3-8fbc-573b6276147f.png)

After 20 minutes it already uses around 400MB

![screenshot_354](https://f.cloud.github.com/assets/21913/1674492/2e39044e-5cfa-11e3-93c8-0846d035f3ea.png)

Eventually it fill the memory and computers will grind to halt

**Comment by tuupola** [comment]
It seems the leak was caused by launching a second Flux slider on non existent element. Minimal code to cause memory leak on Safari is the following:

``` javascript
var slider = new flux.slider("#nosuch");
```

Note that it leaks only if `#nosuch` does not exist.

**Comment by joelambert** [comment]
Thanks for the report and for documenting the cause - will take a look to see if I can address this

**Comment by slaFFik** [comment]
Having the same issue. Using 1.4.4 which was released on 14 Mar 2012.
Why the task is closed? As it was created after the latest release and code commit in the repo.
