### ISSUE TITLE
Can't get transitions to work?

### ISSUE THREAD

**Issue by ashearlam** [joelambert/Flux-Slider#52]
Ok, so before anyone else says. I'm more or less a noob when it comes to certain things!

I have been able to implement the slider, however i cannot specify a transition? Am i calling it in the wrong place?

```
 window.f = new flux.slider('#slider',  {
            autoplay: true,
                pagination: false,
                transitions: bars3d

});
```

});

**Comment by joelambert** [comment]
Almost right, the transitions parameter can be one or more so you need to specify it as an array, you also need to make sure each transitions is a string. Try something like this:

```
window.f = new flux.slider('#slider',  {
        autoplay: true,
        pagination: false,
        transitions: ['bars3d']
});
```

**Comment by ashearlam** [comment]
ahh.. sorry about that and thanks very much!! Genius slider btw :)
