### ISSUE TITLE
more sliders in single page with controls

### ISSUE THREAD

**Issue by lucapost** [joelambert/Flux-Slider#7]
Can anybody show me how to add 2 or more sliders in single page?

thanks,
Luca

**Comment by joelambert** [comment]
Hi Luca,

Here is a simple example of setting up two sliders on the same page: http://jsbin.com/inide4/2

Hope that helps?

**Comment by lucapost** [comment]
yep, is there a way to add controls (play, pause, next, prev) for both?

**Comment by joelambert** [comment]
Yeah absolutely, give the [README](https://github.com/joelambert/Flux-Slider/blob/master/README.md) a look. It describes the API.

Essentially every `flux.slider` object you create can be controlled via Javascript, so you can do something like this:

```
window.f = new flux.slider('#slider1');
window.f.next() // Show next image
window.f.prev() // Show previous image
window.f.stop() // Stop the slider from autoadvancing
window.f.start() // Start autoadvancing
```

There is a bunch of extra settings you can do with the above such as specifying specific transitions etc but take a look at the docs.

Flux has been designed to be as flexible as possible, which means that it doesn't come with a pre-defined next/prev transport UI. But the API means you can hook up your own UI, just how you want it to look!

**Comment by lucapost** [comment]
html: http://dpaste.com/557830/
javascript: http://dpaste.com/557831/
css: http://dpaste.com/557832/

can you help me to modify this code to insert 2 or more gallery in single page?
thanks, 
Luca.

**Comment by lucapost** [comment]
can you show me how to add controls for 2 slides in single page?

**Comment by joelambert** [comment]
Hi Luca,

I'm afraid I'm snowed under with work at the moment, I'll get back to you ASAP but its likely to be a couple of weeks

Thanks

Joe

**Comment by lucapost** [comment]
up :D

**Comment by lucapost** [comment]
can you help me? please -.-

**Comment by lucapost** [comment]
if nobody help me, I think that will change the gallery :-(

**Comment by joelambert** [comment]
Luca, the links you've posted are no longer working. I'm also incredibly snowed under with work at the moment.

The [jsbin](http://jsbin.com/inide4/2) link I posted above shows how to setup two sliders on one page, although some of the images no longer work the code is still correct.

**Comment by lucapost** [comment]
can ou add controls for both gallery in your example plz?

**Comment by Allegra** [comment]
Can you help me too? I need these feature .

**Comment by joelambert** [comment]
Here is an example which has controls for `prev` & `next`.

http://jsbin.com/inide4/4

I suggest you use proper event binding rather than `onclick` but the code is the same.

**Comment by lucapost** [comment]
wow! thanks!

**Comment by Allegra** [comment]
OH! thanks guys!

**Comment by joelambert** [comment]
Glad this helped, sorry it took a while I've been crazy busy last few weeks. Drop me a link when you're up and running, would love to see what you're working on.

Gonna close this ticket now

**Comment by lucapost** [comment]
uhm... is there a way to pause with one click all sliders in one page?

**Comment by joelambert** [comment]
Yes, just call the `stop()` function on all the sliders you created on the `click` event for whatever dom element you want to be the stop button.

If you'd like to hire me to help you get this all working then feel free to send me a private message.
