### ISSUE TITLE
Callback after imageanimation ends.

### ISSUE THREAD

**Issue by rphl** [joelambert/Flux-Slider#8]
It it possible to set a callback that is called if the imageanimation ends? I would like to use flux as clickable slider.

```
 <a href="#dynamicUrlChangedByFluxl">
 <div id="slider">
     <img><img><img>
</div>
</a>
```

Thx.

**Comment by joelambert** [comment]
Sounds like a good idea, I'll take a look at this when I get back from leave next week!

I guess this could either be in the form of a callback or the flux element could fire an event which you could listen/bind to. I'll have to think about which is more appropriate.

Thanks for the suggestion!

**Comment by joelambert** [comment]
I've pushed some code to the GitHub repo (pre-release) for this. I've also updated the README with instructions of how to use it. Let me know if this is suitable for your needs.
